#!/usr/bin/perl -w

use BOSS::Config;
use PerlLib::SwissArmyKnife;

$specification = q(
	-t		Timestamp
);

my $config =
  BOSS::Config->new
  (Spec => $specification);
my $conf = $config->CLIConfig;
# $UNIVERSAL::systemdir = "/var/lib/myfrdcsa/codebases/minor/system";

my $text;
if (exists $conf->{'-t'}) {
  $text = DateTimeStamp();
} else {
  $text = GetDateYYYYMMDD();
}

print $text;
