#!/usr/bin/perl -w

use Capability::CoreferenceResolution::UniLang::Agent;

use UniLang::Agent::Agent;
use UniLang::Util::Message;

$UNIVERSAL::agent = UniLang::Agent::Agent->new
  (
   Name => "CoreferenceResolution",
   ReceiveHandler => \&Receive,
  );

$UNIVERSAL::coreferenceresolution = Capability::CoreferenceResolution::UniLang::Agent->new();

sub Receive {
  my %args = @_;
  $UNIVERSAL::coreferenceresolution->ProcessMessage
    (Message => $args{Message});
}

$UNIVERSAL::coreferenceresolution->Execute
  ();
