#!/usr/bin/perl -w

use Capability::WSD::UniLang::Agent;

use UniLang::Agent::Agent;
use UniLang::Util::Message;

$UNIVERSAL::agent = UniLang::Agent::Agent->new
  (
   Name => "WSD",
   ReceiveHandler => \&Receive,
  );

$UNIVERSAL::wsd = Capability::WSD::UniLang::Agent->new();

sub Receive {
  my %args = @_;
  $UNIVERSAL::wsd->ProcessMessage
    (Message => $args{Message});
}

$UNIVERSAL::wsd->Execute
  ();
