#!/usr/bin/perl -w

use System::Cyc;

use UniLang::Agent::Agent;
use UniLang::Util::Message;

use Data::Dumper;

$UNIVERSAL::agent = UniLang::Agent::Agent->new
  (Name => "Cyc",
   ReceiveHandler => \&Receive);
$UNIVERSAL::agent->DoNotDaemonize(1);
$UNIVERSAL::cyc = System::Cyc->new();
# $UNIVERSAL::cyc->StartServer;

sub Receive {
  my %args = @_;
  $UNIVERSAL::cyc->ProcessMessage
    (Message => $args{Message});
}

$UNIVERSAL::cyc->Execute();
