#!/usr/bin/perl -w

use System::Enju::UniLang::Agent;

use UniLang::Agent::Agent;
use UniLang::Util::Message;

$UNIVERSAL::agent = UniLang::Agent::Agent->new
  (
   Name => "Enju",
   ReceiveHandler => \&Receive,
  );

$UNIVERSAL::enju = System::Enju::UniLang::Agent->new();

sub Receive {
  my %args = @_;
  $UNIVERSAL::enju->ProcessMessage
    (Message => $args{Message});
}

$UNIVERSAL::enju->Execute
  ();
